### ISSUE TITLE
Headshots / arrow bouncing off monsters

### ISSUE THREAD

**Issue by enarth** [Blueteak/QuiVrReporting#9] opened 2017-02-01 11:36 UTC
Version: 0.33.7
Headshots still don't always register, and arrow don't always hit where they should
Arrows bouncing off monster for no reason

**Comment by Blueteak** [comment] 2017-02-01 22:33
This should be fixed in 0.33.8, will update here when the patch goes live and I can get more quantitative data that the issue is indeed fixed.

**Comment by enarth** [comment] 2017-02-02 11:29
i confirm, it seems to be corrected in build 0.33.8

**Closed as completed** 2017-02-02 11:28 UTC
Labels: bug
